import React from "react";
import Head from "next/head";
import Navbar from "../Navbar";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>3D Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <main>{children}</main>
    </>
  );
}
